### ISSUE TITLE
Header tabella stati emergenza

### ISSUE THREAD

**Issue by sabas** [italiasicura/mappa-italiasicura#4]
Probabilmente bisognerebbe eliminare la prima e la terza riga nel file scaricabile
![image](https://cloud.githubusercontent.com/assets/1304918/12338037/da0ce1fa-bb0d-11e5-87a5-b9d8ffd2042d.png)

**Comment by groundrace** [comment]
purtroppo non abbiamo modo di intervenire su quel file ne sul suo formato (XLSX) ! E' possibile che a breve concorderemo modalità leggermente diverse, proponendo formati più portabili
