### ISSUE TITLE
Inserire classificazione ente negli open data

### ISSUE THREAD

**Issue by sabas** [italiasicura/mappa-italiasicura#5]
Ad esempio
![image](https://cloud.githubusercontent.com/assets/1304918/12338263/1f4385c0-bb0f-11e5-90d3-adceb14fe968.png)

Si potrebbe suddividere il dato per permettere aggregazioni diverse? (esempio provincia,GE,Genova) Oppure esiste un codice meccanografico dell'ente comune a tutti ? (il codice istat è solo per comuni/regioni/province)

**Comment by groundrace** [comment]
Purtroppo queste informazioni, sono gestite direttamente da ISPRA nella base dati ReNDiS e al momento non abbiamo modo di intervenire su questo formato. Tuttavia nella revisione che stiamo facendo è prevista l'integrazione in #italisicura di altre tre basi dati ed è plausibile che il formato open data sarà rivisto, esteso e migliorato anche per indirizzare richieste come questa.
